### ISSUE TITLE
webui.py能正常运行，运行api.py 报错

### ISSUE THREAD

**Issue by hjj-lmx** [jianchang512/cosyvoice-api#3]
D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\torch\_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
Traceback (most recent call last):
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\pydoc.py", line 439, in safeimport
    module = __import__(path)
  File "E:\CosyVoice\cosyvoice\flow\flow_matching.py", line 16, in <module>
    from matcha.models.components.flow_matching import BASECFM
ModuleNotFoundError: No module named 'matcha'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\CosyVoice\api.py", line 40, in <module>
    tts_model = CosyVoice('pretrained_models/CosyVoice-300M-SFT')
  File "E:\CosyVoice\cosyvoice\cli\cosyvoice.py", line 29, in __init__
    configs = load_hyperpyyaml(f)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\hyperpyyaml\core.py", line 188, in load_hyperpyyaml
    hparams = yaml.load(yaml_stream, Loader=loader)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\ruamel\yaml\constructor.py", line 116, in get_single_data
    return self.construct_document(node)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\ruamel\yaml\constructor.py", line 120, in construct_document
    data = self.construct_object(node)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\ruamel\yaml\constructor.py", line 188, in construct_non_recursive_object
    for _dummy in generator:
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\ruamel\yaml\constructor.py", line 633, in construct_yaml_map
    value = self.construct_mapping(node)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\ruamel\yaml\constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\ruamel\yaml\constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\ruamel\yaml\constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\hyperpyyaml\core.py", line 480, in _construct_object
    args, kwargs = _load_node(loader, node)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\hyperpyyaml\core.py", line 434, in _load_node
    kwargs = loader.construct_mapping(node, deep=True)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\ruamel\yaml\constructor.py", line 429, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\ruamel\yaml\constructor.py", line 244, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\ruamel\yaml\constructor.py", line 147, in construct_object
    data = self.construct_non_recursive_object(node)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\ruamel\yaml\constructor.py", line 183, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\site-packages\hyperpyyaml\core.py", line 470, in _construct_object
    callable_ = pydoc.locate(callable_string)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\pydoc.py", line 1719, in locate
    nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
  File "D:\Program Files\miniconda3\envs\cosyvoice\lib\pydoc.py", line 454, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in cosyvoice.flow.flow_matching - ModuleNotFoundError: No module named 'matcha'

**Comment by jianchang512** [comment]
重新下载 api.py 覆盖

或 pip install matcha-tts

**Comment by hjj-lmx** [comment]
> 重新下载 api.py 覆盖
> 
> 或 pip install matcha-tts

可不可以，把原项目中的third_party/Matcha-TTS删掉，直接使用pip安装，这样你的api是不是也需要修改，没必要引用hird_party/Matcha-TTS这个了

**Comment by jianchang512** [comment]
不需要修改 api.py

**Comment by hjj-lmx** [comment]
为什么要把“。”全部替换成“，”，如果是长文本，应该怎么分段处理，不然内存扛不住吧

**Comment by cpken** [comment]
不需要安装 `matcha-tts` 包，运行以下代码即可

```shell
$ export PYTHONPATH=third_party/Matcha-TTS
$ python api.py
```

**Comment by hjj-lmx** [comment]
> 不需要安装 `matcha-tts` 包，运行以下代码即可
> 
> ```shell
> $ export PYTHONPATH=third_party/Matcha-TTS
> $ python api.py
> ```

已经解决了，谢谢

**Comment by jianchang512** [comment]
> 为什么要把“。”全部替换成“，”，如果是长文本，应该怎么分段处理，不然内存扛不住吧

长文本分行，按行处理的。

之前测试时发现，经常会到“。”时中断。不知是不是bug，为减少出错，就改为逗号了。

**Comment by hjj-lmx** [comment]
> > 为什么要把“。”全部替换成“，”，如果是长文本，应该怎么分段处理，不然内存扛不住吧
> 
> 长文本分行，按行处理的。
> 
> 之前测试时发现，经常会到“。”时中断。不知是不是bug，为减少出错，就改为逗号了。

There is no such class as cosyvoice.llm.llm.TransformerLM
这个是什么问题，加载模型的时候报的

**Comment by kaidachen** [comment]
> > > 为什么要把“。”全部替换成“，”，如果是长文本，应该怎么分段处理，不然内存扛不住吧
> > 
> > 
> > 长文本分行，按行处理的。
> > 之前测试时发现，经常会到“。”时中断。不知是不是bug，为减少出错，就改为逗号了。
> 
> There is no such class as cosyvoice.llm.llm.TransformerLM 这个是什么问题，加载模型的时候报的 CosyVoice(os.path.join(hub_dir, 'checkpoints/CosyVoice/CosyVoice-300M-SFT')) 我把模型的路径改了

我也遇到There is no such class as cosyvoice.llm.llm.TransformerLM的问题，请问您解决了吗？怎么解决的？谢谢

**Comment by cpken** [comment]
代码贴出来看一下

**Comment by Dev-MetInt** [comment]
求问咋解决的，碰到了同样的问题
