### ISSUE TITLE
 returned non-zero exit status 254

### ISSUE THREAD

**Issue by cpken** [jianchang512/cosyvoice-api#4]
一个 700 多字的长文本，按行生成了若干个音频，在执行合成音频的时候报错了
```
Command '['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-f', 'concat', '-safe', '0', '-i', '/CosyVoice/tmp/1721208437.3936045.txt', '-c:a', 'copy', '/CosyVoice/tmp/20240717-172632--tts.wav']' returned non-zero exit status 254.
Command '['ffmpeg', '-hide_banner', '-ignore_unknown', '-y', '-f', 'concat', '-safe', '0', '-i', '/CosyVoice/tmp/1721208437.3936045.txt', '-c:a', 'copy', '/CosyVoice/tmp/20240717-172632--tts.wav']' returned non-zero exit status 254.
```

报错来源
api.py
```python
subprocess.run(["ffmpeg", "-hide_banner", "-ignore_unknown", "-y", "-f", "concat", "-safe", "0", "-i",
                        f'{tmp_dir}/{txt_name}', "-c:a", "copy", tmp_dir + '/' + outname],
                       stdout=subprocess.PIPE,
                       stderr=subprocess.PIPE,
                       encoding="utf-8",
                       check=True,
                       text=True,
                       creationflags=0 if sys.platform != 'win32' else subprocess.CREATE_NO_WINDOW)
```

**Comment by jianchang512** [comment]
如果代码不是今天新拉取的，就拉取下。如果是，执行下下面命令看看什么报错

`ffmpeg  -hide_banner -ignore_unknown  -y -f concat -safe 0 -i  /CosyVoice/tmp/1721208437.3936045.txt -c:a  copy /CosyVoice/tmp/20240717-172632--tts.wav`

**Comment by cpken** [comment]
运行代码
```shell
ffmpeg  -hide_banner -ignore_unknown  -y -f concat -safe 0 -i  ./tmp/1721210953.4555585.txt -c:a  copy ./tmp/1721210909.3303192-0-tts.wav
```
运行了，报了如下错误
```
[concat @ 0x55ac821c39c0] Impossible to open '/CosyVoice/tmp//CosyVoice/tmp/1721210909.3303192-0-tts.wav'
[in#0 @ 0x55ac821c3880] Error opening input: No such file or directory
Error opening input file ./tmp/1721210953.4555585.txt.
Error opening input files: No such file or directory
```

**Comment by cpken** [comment]
我解决了路径的问题，又遇到了另外一个问题，依然是路径的问题。
```
[2024-07-18 09:51:36,702] ERROR in app: Exception on /tts [POST]
Traceback (most recent call last):
  File "/conda_env/CosyVoice/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/conda_env/CosyVoice/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/conda_env/CosyVoice/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/conda_env/CosyVoice/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "api.py", line 205, in tts
    return send_file(outname, mimetype='audio/x-wav')
  File "/conda_env/CosyVoice/lib/python3.8/site-packages/flask/helpers.py", line 499, in send_file
    return werkzeug.utils.send_file(  # type: ignore[return-value]
  File "/conda_env/CosyVoice/lib/python3.8/site-packages/werkzeug/utils.py", line 428, in send_file
    stat = os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/CosyVoice/20240718-095052--tts.wav'
ERROR:api:Exception on /tts [POST]
Traceback (most recent call last):
  File "/conda_env/CosyVoice/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/conda_env/CosyVoice/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/conda_env/CosyVoice/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/conda_env/CosyVoice/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "api.py", line 205, in tts
    return send_file(outname, mimetype='audio/x-wav')
  File "/conda_env/CosyVoice/lib/python3.8/site-packages/flask/helpers.py", line 499, in send_file
    return werkzeug.utils.send_file(  # type: ignore[return-value]
  File "/conda_env/CosyVoice/lib/python3.8/site-packages/werkzeug/utils.py", line 428, in send_file
    stat = os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/CosyVoice/20240718-095052--tts.wav'
```
